### ISSUE TITLE
Backup: Attic vs. Borg

### ISSUE THREAD

**Issue by ypid** [FiaasCo/fiaas#1]
Just a quick note. [Attic](https://github.com/jborg/attic) has not been updated recently. It has been forked into [Borg Backup](https://github.com/borgbackup/borg). What are your thoughts on that? There is also a Ansible role for that which you might be able to use: https://github.com/andreaswolf/ansible-role-borgbackup

**Comment by stroobl** [comment]
We're aware of Borg Backup, but it didn't exist when started this project (in private). The main reason we didn't switch over are some of the scary messages at the bottom of the Borg README. (not compatible with Attic, excpect that we will break compatibility repeatedly...) We also didn't notice any real issues with Attic till now. And finally: at the start of Borg backup it was also not really clear if some of the changes would be merged back to Attic.

That being said, since Attic development appears to be stopped, we should probably migrate to Borg too. Do you use Borg?

**Comment by ypid** [comment]
Sure, works great. I guess it is time to for you switch then :wink:

**Comment by srvg** [comment]
FWIW, I recently started using borg backup in combo with an offering from rsync.net.

So far so good....

**Comment by stroobl** [comment]
Work in progress @ https://github.com/FiaasCo/fiaas/tree/borg/playbooks/roles/borgbackup
Comments welcome.
I still have to check some of the changed attic<>borg config options.
